config/routes.rb
Rails.application.routes.draw do
  resources :reports
  resources :pets
  resources :searches
  get 'static_pages/about'
  root 'pets#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
class Pet < ApplicationRecord
    validates :image_URL, presence: true, url:true
    validates :topictype, presence: true
    validates :pettype, presence: true
    
    DATE_VALID = /\A\d+[\/]\d+[\/]\d+\z/
    validates :date, presence: true
    validates :describe, presence: true, length:{maximum:1000}
    
    validates :location, presence: true, length:{maximum:250}
    CONTACT_VALID = /\A[+-]?\d+\z/
    validates :telephonenumber, presence: true, length:{ maximum:16}, format:{ with:CONTACT_VALID,message: "Should be Number"}
    
    
    def self.search(search)
        if search
            where( ["describe LIKE ?", "%#{search}%"] ).or(where( ["Location LIKE ?", "%#{search}%"] ))
        else
            all
            
        end
    end

end

app/models/report.rb
class Report < ApplicationRecord
    validates :topic_url, presence: true, url:true
    validates :evidence_url, presence: true, url:true
end

app/models/search.rb
class Search < ApplicationRecord
    
    
    TOPIC_REGEX = /Lost|Found/
    validates :topictype, presence: true, format:{with:TOPIC_REGEX}
    
    PET_REGEX = /Cat|Dog|Other/
    validates :pettype, presence: true, format:{with:PET_REGEX}
    
    def search_pets
       pets = Pet.all
       
       
       pets = pets.where( ["describe LIKE ?", "%#{keywords}%"] ).or(pets.where( ["location LIKE ?", "%#{keywords}%"] ))
       pets = pets.where( ["topictype = ?", "#{topictype}"] ) if topictype.present?
       pets = pets.where( ["pettype = ?", "#{pettype}"] ) if pettype.present?
       
       return pets
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  # GET /pets
  # GET /pets.json
  def index
    @pets = Pet.search(params[:search])
  end

  # GET /pets/1
  # GET /pets/1.json
  def show
  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets
  # POST /pets.json
  def create
    @pet = Pet.new(pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to @pet, notice: 'Pet was successfully created.' }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1
  # PATCH/PUT /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to @pet, notice: 'Pet was successfully updated.' }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to pets_url, notice: 'Pet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pet_params
      params.require(:pet).permit(:image_URL, :topictype, :pettype, :date, :describe, :location, :telephonenumber)
    end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:topic_url, :evidence_url)
    end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
    def new
        @search = Search.new
    end
    
    def create
        @search = Search.create(search_params)
        redirect_to @search
    end
    
    def show
        @search = Search.find(params[:id])
    end
    
    
    
    
    private
    
    def search_params
        params.require(:search).permit(:keywords, :topictype, :pettype)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title><%= yield(:title) %> | PetLostAndFound</title>
 <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
    
        <link href="petLostAndFound/app/assets/stylesheets/bootstrap-material-design.css" rel="stylesheet">
  </head>
  <body>
     <div class="container">

      <div class="masthead">
        <h3 class="text-muted">Pet Lost & Found</h3>

        <nav class="navbar navbar-expand-md navbar-light bg-light rounded mb-3">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <ul class="navbar-nav text-md-center nav-justified w-100">
              <li class="nav-item active">
                <a class="nav-link" href="http://pet-lostandfound.herokuapp.com">Home <span class="sr-only">(current)</span></a>
              
                <a class="nav-link" href="http://pet-lostandfound.herokuapp.com/static_pages/about">About</a>
              </li>
              
            </ul>
          </button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav text-md-center nav-justified w-100">
              <li class="nav-item active">
                <a class="nav-link" href="http://pet-lostandfound.herokuapp.com">Home <span class="sr-only">(current)</span></a>
              </li>
            
              <li class="nav-item">
                <a class="nav-link" href="http://pet-lostandfound.herokuapp.com/static_pages/about">About</a>
              </li>
              
            </ul>
          </div>
        </nav>
      </div>
    
  
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pets/_form.html.erb
<%= form_with(model: pet, local: true) do |form| %>
  <% if pet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pet.errors.count, "error") %> prohibited this pet from being saved:</h2>

      <ul>
      <% pet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="form-group">
  <div class="field alert alert-danger" role="alert">
    <%= form.label :image_URL%>
    <%= form.text_field :image_URL, id: :pet_image_URL %>

    
  </div>

  <div class="field alert alert-warning" role="alert">
    <div style="float: left;"><%= form.label :pettype, "Topic Type:" %></div>
    <div style="float: left;"><%= form.radio_button :topictype, "Lost", :checked => true %></div>
    <div style="float: left;"><%= form.label :topictype, "Lost/", :value => "Lost"  %></div>
    <div style="float: left;"><%= form.radio_button :topictype, "Found" %></div>
    <%= form.label :topictype, "Found", :value => "Found" %>
  </div>
  <div class="field alert alert-primary" role="alert">
    <div style="float: left;"><%= form.label :pettype, "Pet Type:" %></div>
    <div style="float: left;"><%= form.radio_button :pettype, "Dog", :checked => true %></div>
    <div style="float: left;"><%= form.label :pettype, "Dog/", :value => "Dog"  %></div>
    <div style="float: left;"><%= form.radio_button :pettype, "Cat" %></div>
    <div style="float: left;"><%= form.label :pettype, "Cat/", :value => "Cat" %></div>
    <div style="float: left;"><%= form.radio_button :pettype, "Other" %></div>
    <%= form.label :pettype, "Other", :value => "Other" %>
  </div>

  <div class="field alert alert-secondary" role="alert">
    <%= form.label :date %>
    <%= form.text_field :date, id: :date %>

  </div>

  <div class="field alert alert-success" role="alert">
    <%= form.label :describe, "Description" %>
    <%= form.text_area :describe, id: :pet_describe %>
  </div>

  <div class="field alert alert-dark" role="alert">
    <%= form.label :location %>
    <%= form.text_area :location, id: :pet_location %>
  </div>

  <div class="field alert alert-info" role="alert">
    <%= form.label :telephonenumber, "Telephone Number" %>
    <%= form.text_field :telephonenumber, id: :pet_telephonenumber %>
  </div>

  <div class="actions col-auto btn btn-primary">
    <%= link_to 'Back',pets_path %>
    <%= form.submit %>
  
  </div>
  </div>

  
  
<% end %>

app/views/pets/edit.html.erb
<% provide(:title, "Edit") %>
<h1>Editing Topic</h1>

<%= render 'form', pet: @pet %>

<%= link_to 'Show', @pet %>

app/views/pets/index.html.erb
<% provide(:title, "Index") %>
<p id="notice"><%= notice %></p>

 <html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="https://fezvrasta.github.io/bootstrap-material-design/favicon.ico">


    <!-- Bootstrap core CSS -->
    <link href="petLostAndFound/app/assets/stylesheets/bootstrap-material-design.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="album.css" rel="stylesheet">
  </head>
 
 <body>


    <section class="jumbotron text-center">
      <div class="container">
        <h1 class="jumbotron-heading">Pet Lost & Found</h1>
        <p class="lead text-muted"></p><!-- For webpage information -->
        <p>
           
                <button  type="button" class="btn btn-info  btn-lg btn-block" role="button" style="background: #FBEFFB;"><%= link_to 'New Topic', new_pet_path %></button>
                <button  type="button" class="btn btn-info  btn-lg btn-block" role="button" style="background: #FBEFFB;"><%= link_to 'Report Topic', new_report_path %></button>
                <button type="button" class="btn btn-info  btn-lg btn-block" role="button" style="background: #FBEFFB;">
                  <%= form_tag pets_path, :method => 'get' do %>
                  <%= text_field_tag :search, params[:search] %>
                  <%= submit_tag "search" %>
                  <% end %>
                   <%= link_to "Advanced Search", new_search_path %>
                </button>
              
          
        
          
        </p>
      </div>
    </section>

    <div class="album text-muted">
      <div class="container">

        <div class="row">
        
          
           <% @pets.each do |pet| %>
            <div class="card" style="background: #FBEFFB;"  >
                           <td class="im" alt="Card image cap"><%= image_tag(pet.image_URL, class: 'list_image',height:'280px') %></td>
                            <td class="list_description">
                          <dl>
                      <dd><B>Topic Type :</B> <%= pet.topictype %></dd>
                      <dd><B>Description :</B> <br><%= truncate(strip_tags(pet.describe),
                         length: 100) %></dd>
                      <dd><B>Location :</B> <%= truncate(strip_tags(pet.location),
                         length: 60) %></dd>
                      <dd class="list_actions btn btn-primary">
                        <%= link_to 'Show More', pet %>
                      </dd>
                    </dl>
                  </td>
              
              
            </div>
            <% end %>
       
        </div>

      </div>
    </div>

    <footer class="text-muted">
      <div class="container">
        <p class="float-right">
          <a href="#">Back to top</a>
        </p>
        <p>CN340 &copy; !</p>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="../../../../assets/js/vendor/popper.min.js"></script>
    <script src="../../../../assets/js/vendor/holder.min.js"></script>
    <script>
      $(function () {
        Holder.addTheme("thumb", { background: "#55595c", foreground: "#eceeef", text: "Thumbnail" });
      });
    </script>
    <script src="petLostAndFound/app/assets/javascripts/bootstrap-material-design.min.js"></script>
   
  </body>
</html>

app/views/pets/new.html.erb
<% provide(:title, "New") %>
<h1>New Topic</h1>

<%= render 'form', pet: @pet %>

app/views/pets/show.html.erb
<% provide(:title, "Show") %>
<p id="notice"><%= notice %></p>

<%= image_tag(@pet.image_URL, height: '400px') %>
<p>
  <strong>Image url:</strong>
  <%= @pet.image_URL %>
</p>

<p>
  <strong>Topic Type:</strong>
  <%= @pet.topictype %>
</p>

<p>
  <strong>Pet Type:</strong>
  <%= @pet.pettype %>
</p>

<p>
  <strong>Date:</strong>
  <%= @pet.date %>
</p>

<p>
  <strong>Description:</strong>
  <%= @pet.describe %>
</p>

<p>
  <strong>Location:</strong>
  <%= @pet.location %>
</p>

<p>
  <strong>Telephoe Number:</strong>
  <%= @pet.telephonenumber %>
</p>

<%= link_to 'Back', pets_path %> |
<%= link_to 'Edit', edit_pet_path(@pet) %>

app/views/reports/_form.html.erb
<%= form_with(model: report, local: true) do |form| %>
  <% if report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field alert alert-danger" role="alert">
    <%= form.label :topic_url %>
    <%= form.text_field :topic_url, id: :report_topic_url %>
  </div>

  <div class="field alert alert-warning" role="alert">
    <%= form.label :evidence_url %>
    <%= form.text_field :evidence_url, id: :report_evidence_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reports/edit.html.erb
<h1>Editing Report</h1>

<%= render 'form', report: @report %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
<% provide(:title, "Reports") %>

<p id="notice"><%= notice %></p>

<h1>Reports</h1>

<table class="report-table">
  <thead>
    <tr>
      <th>Topic url</th>
      <th>Evidence url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td><%= link_to "#{report.topic_url}","#{report.topic_url}" %></td>
        <td><%= link_to "#{report.evidence_url}", "#{report.evidence_url}" %></td>
        <td><%= link_to 'DeleteReport', report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'DeleteTopic',  "#{report.topic_url}" , method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Report', new_report_path %>

app/views/reports/new.html.erb
<% provide(:title, "New Report") %>
<h1>New Report</h1>

<%= render 'form', report: @report %>

<%= link_to 'Back', pets_path %>

app/views/reports/show.html.erb
<% provide(:title, "Show Report") %>
<p id="notice"><%= notice %></p>

<p>
  <strong>Topic url:</strong>
  <%= @report.topic_url %>
</p>

<p>
  <strong>Evidence url:</strong>
  <%= @report.evidence_url %>
</p>

<%= link_to 'Edit', edit_report_path(@report) %> |
<%= link_to 'Back', pets_path %>

app/views/searches/new.html.erb
<% provide(:title, "Search") %>
<h1>Advanced Search</h1>

<%= form_for @search, html: {class: "pure-form"} do |s| %>

<div class="field alert alert-danger" role="alert">
    <%= s.label :keywords %><br />
    <%= s.text_field :keywords %>
</div>

<div class="field alert alert-warning" role="alert">
    <div style="float: left;"><%= s.label :pettype, "Topic Type:" %></div>
    <div style="float: left;"><%= s.radio_button :topictype, "Lost", :checked => true %></div>
    <div style="float: left;"><%= s.label :topictype, "Lost/", :value => "Lost"  %></div>
    <div style="float: left;"><%= s.radio_button :topictype, "Found" %></div>
    <%= s.label :topictype, "Found", :value => "Found" %>
    <br>
  </div>
  <div class="field alert alert-primary" role="alert">
    <div style="float: left;"><%= s.label :pettype, "Pet Type:" %></div>
    <div style="float: left;"><%= s.radio_button :pettype, "Dog", :checked => true %></div>
    <div style="float: left;"><%= s.label :pettype, "Dog/", :value => "Dog"  %></div>
    <div style="float: left;"><%= s.radio_button :pettype, "Cat" %></div>
    <div style="float: left;"><%= s.label :pettype, "Cat/", :value => "Cat" %></div>
    <div style="float: left;"><%= s.radio_button :pettype, "Other" %></div>
    <%= s.label :pettype, "Other", :value => "Other" %>
    <br>
  </div>

<div class="action">
    <%= s.submit "Search", class: "pure-button pure-button-primary" %>
</div>


<% end %>

<%= link_to 'back', pets_path %>

app/views/searches/show.html.erb
<% provide(:title, "Search Result") %>


<h1>Search Result</h1>

<p><%= link_to 'Back', new_search_path %></p>

<% if @search.search_pets.empty? %>

    <p>No Records Found</p>
    
<% else %>
 
 <html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="https://fezvrasta.github.io/bootstrap-material-design/favicon.ico">


    <!-- Bootstrap core CSS -->
    <link href="petLostAndFound/app/assets/stylesheets/bootstrap-material-design.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="album.css" rel="stylesheet">
  </head>
 
 <body>



    <div class="album text-muted">
      <div class="container">

        <div class="row">
        
          
          <% @search.search_pets.each do |pet| %>
            <div class="card" style="background: #FBEFFB; " >
                           <td class="im" alt="Card image cap"><%= image_tag(pet.image_URL, class: 'list_image',height:'280px') %></td>
                            <td class="list_description">
                          <dl>
                      <dd><B>Topic Type :</B> <%= pet.topictype %></dd>
                      <dd><B>Description :</B> <br><%= truncate(strip_tags(pet.describe),
                         length: 100) %></dd>
                      <dd><B>Location :</B> <%= truncate(strip_tags(pet.location),
                         length: 60) %></dd>
                      <dd class="list_actions btn btn-primary">
                        <%= link_to 'Show More', pet %>
                      </dd>
                    </dl>
                  </td>
              
              
            </div>
            <% end %>
       
        </div>

      </div>
    </div>

    <footer class="text-muted">
      <div class="container">
        <p class="float-right">
          <a href="#">Back to top</a>
        </p>
        <p>CN340 &copy; !</p>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="../../../../assets/js/vendor/popper.min.js"></script>
    <script src="../../../../assets/js/vendor/holder.min.js"></script>
    <script>
      $(function () {
        Holder.addTheme("thumb", { background: "#55595c", foreground: "#eceeef", text: "Thumbnail" });
      });
    </script>
    <script src="petLostAndFound/app/assets/javascripts/bootstrap-material-design.min.js"></script>
   
  </body>
</html>

<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>Pet Lost&Found database</h1>
<p>
    <h2>Production teams</h2>
    Tuvashit Boonlar   5810520196<br>
    Suppanut Rodpon    5810613181
</p>
<br><br>
<h2>Requirement</h2>
<p>
    1.สามารถตั้งหัวข้อเรื่องสำหรับตามหาสัตว์เลี้ยงที่หายไปได้<br>
    2.สามารถตั้งหัวข้อเรื่องสำหรับตามหาเจ้าของสัตว์เลี้ยงที่พบได้<br>
    3.สามารถค้นหาหัวข้อเรื่องโดยอาศัย keyword
</p>

<br><br>

<h2>Features</h2>
Iteration 1<br>
<%= image_tag("01.png", alt: "feature1")%><br><br>
<%= image_tag("02.png", alt: "feature2")%><br><br><br>
Iteration 2<br>
<%= image_tag("03.png", alt: "feature3")%><br><br>
<%= image_tag("04.png", alt: "feature4")%><br><br><br>
Iteration 3<br>
<%= image_tag("05.png", alt: "feature5")%>
<br><br>

<h2>ER-Diagram</h2>
<%= image_tag("diagram.png", alt: "diagram")%>
<br><br>

<h2>Link</h2>
<p>
    Pivotal tracker : <a href="https://www.pivotaltracker.com/n/projects/2124908">https://www.pivotaltracker.com/n/projects/2124908</a><br>
    Repo bitbucket : <a href="https://bitbucket.org/suppanutfknz/project">https://bitbucket.org/suppanutfknz/project</a><br>
    Iteration0 Presentation : <a href="https://www.youtube.com/watch?v=JYgKs6bINHc">https://www.youtube.com/watch?v=JYgKs6bINHc</a><br>
    Final Presentation : <a href="https://www.youtube.com/watch?v=1rpLabwLs_g">https://www.youtube.com/watch?v=1rpLabwLs_g</a><br>
    Poster : <a href="https://goo.gl/4GaWAH">https://goo.gl/4GaWAH</a>
</p>


<h2>Poster</h2>
<%= image_tag("https://www.picz.in.th/images/2017/12/05/Pet-lostAndFound.jpg", alt: "Poster", width: '500px')%>

<br><br>